spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/esport_portal}
spring.datasource.username=${POSTGRES_USER:esport_user}
spring.datasource.password=${POSTGRES_PASSWORD:esport_password}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
